version: "3.6"
services:
  frontend:
    build:
      context: $PWD/../../frontend
      dockerfile: $PWD/frontend/Dockerfile
    restart: always
    ports:
      - "3000:3001"
    expose:
      - "3001"
      - "443"
    environment:
      - VIRTUAL_HOST=travel.gregsithole.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=travel.gregsithole.com
      - LETSENCRYPT_EMAIL=gregsithole@hotmail.co.za

networks:
  default:
    external:
      name: nginx-proxy