version: "3.6"
services:
  travel:
    build:
      context: $PWD/../..
      dockerfile: $PWD/travel/Dockerfile
    restart: always
    ports:
      - "3000:81"
    expose:
      - "81"
      - "443"
    environment:
      - VIRTUAL_HOST=travel.gregsithole.com
      - VIRTUAL_PORT=81
      - LETSENCRYPT_HOST=travel.gregsithole.com
      - LETSENCRYPT_EMAIL=gregsithole@hotmail.co.za