version: "3.6"
services:
  frontend:
    build:
      context: $PWD/../../frontend
      dockerfile: $PWD/frontend/Dockerfile
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=gregsithole.com, www.gregsithole.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=gregsithole.com, www.gregsithole.com
      - LETSENCRYPT_EMAIL=gregsithole@hotmail.co.za

networks:
  default:
    external:
      name: nginx-proxy