version: "3.6"
services:
  travel:
    build:
      context: $PWD/../..
      dockerfile: $PWD/travel/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=travel.gregsithole.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=travel.gregsithole.com
      - LETSENCRYPT_EMAIL=gregsithole@hotmail.co.za

networks:
  default:
    external:
      name: nginx-proxy